server:
  ssl:
    enabled: false
    key-store-type: JKS
    key-alias: aone.my.id
    key-store-password:
    key-store: classpath:ssl.jks
    key-password:
spring:
  cloud:
    gateway:
      x-forwarded.for-enabled: false
      x-forwarded.host-enabled: false
      x-forwarded.port-enabled: false
      x-forwarded.proto-enabled: false
      x-forwarded.prefix-enabled: false
      x-forwarded.for-append: false
      x-forwarded.host-append: false
      x-forwarded.port-append: false
      x-forwarded.proto-append: false
      x-forwarded.prefix-append: false
      forwarded.enabled: false
  application:
    name: gwproxy
gw:
  proxy:
    http:
      enable: true
      host: localhost
      port: 8080
  cors:
    origin:
      - "*"
      - http://localhost:3000
      - http://localhost:8080
  records:
    - id: apigw_dynamic_host_route
      predicate: 10.0.118.39:5555
      uri: http://10.0.118.39:5555
      cache-config: 3|30
    - id: coin_gecko
      predicate: api.geckoterminal.com
      uri: https://api.geckoterminal.com
      cache-config: 3|10
      prefix-path: /api/v2