spring:
  application:
    name: gwproxy
gw:
  cors:
    origin:
      - http://localhost:3000
      - http://localhost:8080
  proxy:
    records:
      - id: apigw_dynamic_host_route
        predicate: 10.0.118.39:5555
        uri: http://10.0.118.39:5555